# Generated by Django 5.2.1 on 2025-05-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=10, unique=True)),
                ("country_name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("independent", models.BooleanField(default=False)),
                ("google_maps_url", models.URLField(blank=True, max_length=500)),
                ("open_street_map_url", models.URLField(blank=True, max_length=500)),
                ("capital_name", models.CharField(blank=True, max_length=255)),
                ("capital_latitude", models.FloatField(blank=True, null=True)),
                ("capital_longitude", models.FloatField(blank=True, null=True)),
                ("flag_png", models.URLField(blank=True, max_length=500)),
                ("flag_svg", models.URLField(blank=True, max_length=500)),
                ("flag_alt", models.CharField(blank=True, max_length=255)),
                ("coat_of_arms_png", models.URLField(blank=True, max_length=500)),
                ("coat_of_arms_svg", models.URLField(blank=True, max_length=500)),
                ("borders_with", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("count_of_requests", models.PositiveIntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NameCountryProbability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("probability", models.FloatField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.country"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.name"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "country")},
            },
        ),
    ]
