# Generated by Django 5.2.1 on 2025-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="coat_of_arms_png",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="country",
            name="coat_of_arms_svg",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag_alt",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag_png",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag_svg",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="country",
            name="google_maps_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="country",
            name="open_street_map_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
